# Generated by Django 5.0.7 on 2024-07-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('descriptions', models.TextField(max_length='400', verbose_name='Descriptions')),
                ('status', models.CharField(choices=[('В очереди', 'В очереди'), ('В процессе', 'В процессе'), ('Завершена', 'Завершена')], max_length=15, verbose_name='Status')),
                ('data_creation', models.DateTimeField(auto_now_add=True, verbose_name='Data creation')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
